### ISSUE TITLE
请教，MIPI与Packed的区别

### ISSUE THREAD

**Issue by ChesterZero** [xiaoqinxing/ImageTools#18]
请教，MIPI与Packed的区别；感谢~

**Comment by xiaoqinxing** [comment]
MIPI与Packed那两个是高通的格式，不是按照16位去对齐的，经过一定的压缩，有特定的格式要求。目前实现的是海思的RAW图格式，没有经过压缩，无论是12bit海思16bit，存储的时候都按照16位存储的。
